-- ─────────────────────────────────────────────────────────────────────────────
-- Party Prompt Game — Seed Data (120 prompts)
-- 50 open-ended + 50 fill-blank (rounds 1 & 2) + 20 finale (round 3)
-- Run AFTER rls.sql in the Supabase SQL editor.
-- ─────────────────────────────────────────────────────────────────────────────

insert into prompts (prompt_text, prompt_type, family_safe, active) values

-- ─── Open-Ended (50) ─────────────────────────────────────────────────────────
('What is the worst thing to bring on an airplane?',                              'open_ended', true, true),
('What would be a terrible name for a superhero?',                                'open_ended', true, true),
('What is something you should never say at a wedding?',                          'open_ended', true, true),
('What would make a terrible pizza topping?',                                     'open_ended', true, true),
('What is the worst advice you could give a new driver?',                         'open_ended', true, true),
('What is the least useful superpower?',                                          'open_ended', true, true),
('What would be the worst pet to have?',                                          'open_ended', true, true),
('What is the strangest thing to find in someone''s attic?',                      'open_ended', true, true),
('What is something you should never bring to a first date?',                     'open_ended', true, true),
('What would be a terrible job for someone afraid of heights?',                   'open_ended', true, true),
('What is the worst gift you could give a grandmother?',                          'open_ended', true, true),
('What would be the worst name for a restaurant?',                                'open_ended', true, true),
('What is the most useless class you could take in school?',                      'open_ended', true, true),
('What would make a bad mascot for a hospital?',                                  'open_ended', true, true),
('What is the worst thing to say to your boss on your first day?',                'open_ended', true, true),
('What would be a horrible way to start a speech?',                               'open_ended', true, true),
('What would be the worst snack to offer at a movie theater?',                    'open_ended', true, true),
('What is the worst thing to find in your cereal?',                               'open_ended', true, true),
('What would make a terrible first impression?',                                  'open_ended', true, true),
('What is a terrible thing to name a baby?',                                      'open_ended', true, true),
('What is the worst thing to accidentally say on a job interview?',               'open_ended', true, true),
('What would be a horrible nickname for a dentist?',                              'open_ended', true, true),
('What is something that should never be made into a board game?',                'open_ended', true, true),
('What would be the worst supervillain name?',                                    'open_ended', true, true),
('What would be a terrible tagline for a hospital?',                              'open_ended', true, true),
('What would make a terrible candle scent?',                                      'open_ended', true, true),
('What is the worst thing to find under a couch cushion?',                        'open_ended', true, true),
('What would be an awful name for a bakery?',                                     'open_ended', true, true),
('What is the worst thing to bring to a potluck?',                                'open_ended', true, true),
('What would make a terrible birthday cake flavor?',                              'open_ended', true, true),
('What is something you should never say to a librarian?',                        'open_ended', true, true),
('What would be a bad name for a law firm?',                                      'open_ended', true, true),
('What is the worst reason to call in sick to work?',                             'open_ended', true, true),
('What would be a terrible plot twist in a kids'' movie?',                        'open_ended', true, true),
('What is the worst thing to say at the top of a roller coaster?',               'open_ended', true, true),
('What would be a terrible theme for a graduation party?',                        'open_ended', true, true),
('What is something you should never put in a birthday card?',                    'open_ended', true, true),
('What would be a bad name for a daycare center?',                                'open_ended', true, true),
('What is the worst thing to find in a birthday cake?',                           'open_ended', true, true),
('What would be an awful invention?',                                             'open_ended', true, true),
('What is the least romantic thing to say on Valentine''s Day?',                  'open_ended', true, true),
('What would be a terrible name for a coffee shop?',                              'open_ended', true, true),
('What is the worst thing to accidentally text your teacher?',                    'open_ended', true, true),
('What would be a horrible talent for a talent show?',                            'open_ended', true, true),
('What is the worst way to end a bedtime story?',                                 'open_ended', true, true),
('What would make a terrible theme park ride?',                                   'open_ended', true, true),
('What is the worst word to describe a pillow?',                                  'open_ended', true, true),
('What would be a terrible team name for a trivia night?',                        'open_ended', true, true),
('What is the worst thing to say when blowing out birthday candles?',             'open_ended', true, true),
('What would be a bad name for a sports team?',                                   'open_ended', true, true),

-- ─── Fill-in-the-Blank (50) ───────────────────────────────────────────────────
('The worst school subject would be Advanced ______.',                            'fill_blank',  true, true),
('My new invention is a machine that automatically ______.',                      'fill_blank',  true, true),
('The rejected theme for the school dance was ______.',                           'fill_blank',  true, true),
('The worst prize in a cereal box would be ______.',                              'fill_blank',  true, true),
('The name of my imaginary pet dragon is ______.',                                'fill_blank',  true, true),
('Scientists discovered that eating too much ______ gives you superpowers.',      'fill_blank',  true, true),
('The world''s worst babysitter''s only skill is ______.',                        'fill_blank',  true, true),
('My dog would make a great ______ if he wasn''t so lazy.',                       'fill_blank',  true, true),
('The new law that nobody asked for bans ______.',                                'fill_blank',  true, true),
('My grandma''s secret recipe includes a surprising amount of ______.',           'fill_blank',  true, true),
('The worst thing to name a boat is ______.',                                     'fill_blank',  true, true),
('The new flavor of ice cream nobody wanted is ______.',                          'fill_blank',  true, true),
('The weirdest thing found in the school lost and found was ______.',             'fill_blank',  true, true),
('A terrible superpower to have would be ______.',                                'fill_blank',  true, true),
('The worst name for a theme park would be ______.',                              'fill_blank',  true, true),
('The world''s most boring museum would have exhibits about ______.',             'fill_blank',  true, true),
('A bad idea for a reality TV show would be ______.',                             'fill_blank',  true, true),
('The most unhelpful self-help book would be titled ______.',                     'fill_blank',  true, true),
('A terrible secret ingredient in a sandwich would be ______.',                  'fill_blank',  true, true),
('The rejected mascot for our town was ______.',                                  'fill_blank',  true, true),
('My new workout program is called ______.',                                      'fill_blank',  true, true),
('The last thing you want to hear from a dentist is ______.',                     'fill_blank',  true, true),
('The worst song to play at a graduation is ______.',                             'fill_blank',  true, true),
('A terrible slogan for a hotel would be ______.',                                'fill_blank',  true, true),
('The town''s weirdest festival celebrates ______.',                              'fill_blank',  true, true),
('A bad superpower to have in school would be ______.',                           'fill_blank',  true, true),
('The worst thing to find on a restaurant menu is ______.',                       'fill_blank',  true, true),
('The most unconvincing Halloween costume would be ______.',                      'fill_blank',  true, true),
('A strange thing to collect would be ______.',                                   'fill_blank',  true, true),
('The worst game show prize would be ______.',                                    'fill_blank',  true, true),
('The most useless app on a phone would be ______.',                              'fill_blank',  true, true),
('The rejected name for a famous candy bar was ______.',                          'fill_blank',  true, true),
('A bad slogan for a dentist office would be ______.',                            'fill_blank',  true, true),
('The world''s worst bedtime story is called ______.',                            'fill_blank',  true, true),
('A terrible name for a band would be ______.',                                   'fill_blank',  true, true),
('The least inspiring motivational poster would say ______.',                     'fill_blank',  true, true),
('A poorly thought-out bumper sticker would say ______.',                         'fill_blank',  true, true),
('The most ridiculous item on a camping checklist is ______.',                    'fill_blank',  true, true),
('The world''s worst superhero team would be called ______.',                     'fill_blank',  true, true),
('The most unnecessary warning label would say ______.',                          'fill_blank',  true, true),
('A terrible vacation destination would be ______.',                              'fill_blank',  true, true),
('A bad slogan for a gym would be ______.',                                       'fill_blank',  true, true),
('The most unhelpful cookbook would be called ______.',                           'fill_blank',  true, true),
('The least appetizing smoothie flavor would be ______.',                         'fill_blank',  true, true),
('The world''s worst magician''s signature trick is ______.',                     'fill_blank',  true, true),
('A bad suggestion for a class field trip would be ______.',                      'fill_blank',  true, true),
('The worst advice from a fortune cookie would be ______.',                       'fill_blank',  true, true),
('The imaginary country I invented is called ______.',                            'fill_blank',  true, true),
('The unexpected side effect of my new medicine is ______.',                      'fill_blank',  true, true),
('The world''s least popular birthday party theme is ______.',                    'fill_blank',  true, true),

-- ─── Finale (20) ─────────────────────────────────────────────────────────────
('Describe your dream vacation in exactly three words.',                          'finale', true, true),
('Summarize your life philosophy in three words.',                                'finale', true, true),
('Describe the best meal ever in three words.',                                   'finale', true, true),
('Sum up Mondays in three words.',                                                'finale', true, true),
('Describe the perfect nap in three words.',                                      'finale', true, true),
('Sum up your cooking skills in three words.',                                    'finale', true, true),
('Describe traffic jams in three words.',                                         'finale', true, true),
('Describe the perfect Saturday in three words.',                                 'finale', true, true),
('Summarize your worst haircut in three words.',                                  'finale', true, true),
('Describe Thanksgiving dinner in three words.',                                  'finale', true, true),
('Sum up the internet in three words.',                                           'finale', true, true),
('Describe a dentist visit in three words.',                                      'finale', true, true),
('Sum up your favorite movie in three words.',                                    'finale', true, true),
('Describe your morning routine in three words.',                                 'finale', true, true),
('Sum up your relationship with exercise in three words.',                        'finale', true, true),
('Describe Mondays before coffee in three words.',                                'finale', true, true),
('Sum up a trip to the grocery store in three words.',                            'finale', true, true),
('Describe your biggest fear in three words.',                                    'finale', true, true),
('Describe your pet (real or imaginary) in three words.',                        'finale', true, true),
('Sum up school in three words.',                                                 'finale', true, true);
