const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.nchc.org.tw/api/interpreter'];
export default async function handler(req,res){
 const service=String(req.query.service||'').toLowerCase();
 try{
  if(service==='flight'){res.setHeader('Cache-Control','s-maxage=5, stale-while-revalidate=10');const lat=Number(req.query.lat),lon=Number(req.query.lon),radius=Math.min(250,Math.max(1,Number(req.query.radius)||50));if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'lat and lon required'});const r=await fetch(`https://api.adsb.lol/v2/point/${lat}/${lon}/${radius}`,{headers:{'User-Agent':'internalapps-flight-explorer/1.0'}});const text=await r.text();res.status(r.status).setHeader('Content-Type',r.headers.get('content-type')||'application/json');return res.send(text)}
  if(service==='cruise'){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');const type=String(req.query.type||'voyages'),allowed={voyages:'/api/voyages',brands:'/api/brands',ships:'/api/ships',search:'/api/search'};if(!allowed[type])return res.status(400).json({error:'Invalid type'});const p=new URLSearchParams();for(const[k,v]of Object.entries(req.query))if(!['service','type'].includes(k)&&v!=null&&v!=='')p.set(k,String(v));const r=await fetch('https://mcp.siloah.travel'+allowed[type]+'?'+p,{headers:{accept:'application/json','User-Agent':'internalapps-cruise-explorer/1.0'}});const text=await r.text();res.status(r.status).setHeader('Content-Type',r.headers.get('content-type')||'application/json');return res.send(text)}
  if(service==='food-geocode'){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const q=String(req.query.q||'').trim().slice(0,200);if(!q)return res.status(400).json({error:'Location is required'});const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=us&q='+encodeURIComponent(q),{headers:{Accept:'application/json','User-Agent':'InternalApps-FoodMap/1.0'}});if(!r.ok)throw Error('Geocoder returned '+r.status);const data=await r.json();res.setHeader('Cache-Control','s-maxage=86400, stale-while-revalidate=604800');return res.status(200).json({results:data.map(x=>({lat:+x.lat,lon:+x.lon,label:x.display_name,type:x.type}))})}
  if(service==='food-places'){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const lat=Number(req.query.lat),lon=Number(req.query.lon),radius=Math.min(Math.max(Number(req.query.radius)||8047,250),40234),allowed=new Set(['restaurant','fast_food','cafe','ice_cream','food_court','bar','pub']),types=String(req.query.types||'restaurant,fast_food,cafe,ice_cream').split(',').filter(x=>allowed.has(x));if(!Number.isFinite(lat)||lat < -90||lat > 90||!Number.isFinite(lon)||lon < -180||lon > 180)return res.status(400).json({error:'Invalid coordinates'});if(!types.length)return res.status(200).json({elements:[]});const re=types.join('|'),query=`[out:json][timeout:25];(nwr["amenity"~"^(${re})$"](around:${Math.round(radius)},${lat},${lon}););out center tags;`;let last='',attempts=[];for(const url of OVERPASS){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8',Accept:'application/json','User-Agent':'InternalApps-FoodMap/1.0'},body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(28000)});if(!r.ok){last=r.status+' '+r.statusText;attempts.push({provider:new URL(url).host,status:r.status,error:last});continue}const data=await r.json();attempts.push({provider:new URL(url).host,status:r.status,count:(data.elements||[]).length});res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=1800');return res.status(200).json({elements:data.elements||[],source:new URL(url).host,attempts})}catch(e){last=e.message}}return res.status(502).json({error:'Food data is temporarily unavailable',detail:last,attempts})}
  if(service==='iheart'){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600');const action=String(req.query.action||'search');if(action==='search'){const q=String(req.query.q||'').trim();if(!q)return res.status(400).json({error:'Missing q'});const r=await fetch('https://api.iheart.com/api/v1/catalog/searchAll?keywords='+encodeURIComponent(q),{headers:{'User-Agent':'InternalApps-ColoradoRadio/1.0',Accept:'application/json'}});const text=await r.text();res.status(r.status).setHeader('Content-Type',r.headers.get('content-type')||'application/json');return res.send(text)}if(action==='station'){const id=String(req.query.id||'').replace(/\D/g,'');if(!id)return res.status(400).json({error:'Missing station id'});const r=await fetch('https://api.iheart.com/api/v2/content/liveStations/'+id,{headers:{'User-Agent':'InternalApps-ColoradoRadio/1.0',Accept:'application/json'}});if(!r.ok)return res.status(r.status).json({error:'iHeart station lookup failed'});const body=await r.json(),station=body?.hits?.[0]||body?.data?.[0]||body,streams=station?.streams||{},stream=streams.secure_hls_stream||streams.hls_stream||streams.secure_shoutcast_stream||streams.shoutcast_stream||streams.stw_stream||streams.secure_pls_stream||streams.pls_stream||Object.values(streams).find(v=>typeof v==='string');return res.status(200).json({id:station?.id||Number(id),iheartId:station?.id||Number(id),name:station?.name||station?.title||`iHeart Station ${id}`,callSign:station?.callLetters||station?.callSign||'',city:station?.city||station?.market?.city||'',state:station?.state||station?.market?.state||'',logo:station?.logo||station?.logoUrl||station?.imageUrl||station?.assets?.logo||'',official:station?.website||station?.url||`https://www.iheart.com/live/${id}/`,stream})}return res.status(400).json({error:'Unknown action'})}
  return res.status(400).json({error:'Unknown service'});
 }catch(e){return res.status(502).json({error:(service||'Proxy')+' request failed',detail:e?.message||String(e)})}
}